from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional

class DocumentValidation(BaseModel):
    """Document validation model for contract information"""
    CustomerName: str = Field(description="Name of the customer or company (Required but if not applicable, N/A)")
    AccountID: Optional[str] = Field(description="Unique identifier for the customer account (Required but if not applicable, N/A)")
    Quote: Optional[str] = Field(description="Quote number reference")
    CommitmentTerms: Optional[str] = Field(description="Terms of commitment specified in the contract (Required but if not applicable, N/A)")
    BuyingProgram: Optional[str] = Field(description="Type of buying program or plan (Required but if not applicable, N/A)")
    CommitmentFee: Optional[float] = Field(description="Fee amount for the commitment (Required but if not applicable, N/A)")
    SavingsPlanCredit: Optional[float] = Field(description="Credit amount from savings plan (Required but if not applicable, N/A)")
    NetPayableFee: Optional[float] = Field(description="Net fee amount payable (Required but if not applicable, N/A)")
    ContactName: Optional[str] = Field(description="Name of the primary contact person (Required but if not applicable, N/A)")
    TermStartDate: Optional[datetime] = Field(description="Start date of the contract term (Required but if not applicable, N/A)")
    RenewalDate: Optional[datetime] = Field(description="Date when the contract is up for renewal (Required but if not applicable, N/A)")
    BillingTerms: Optional[str] = Field(description="Terms and conditions for billing (Required but if not applicable, N/A)")
    PaymentTerms: Optional[str] = Field(description="Terms and conditions for payment (Required but if not applicable, N/A)")
    PaymentMethod: Optional[str] = Field(description="Method of payment specified (Required but if not applicable, N/A)")
    VATID: Optional[str] = Field(description="VAT identification number")
    PO: Optional[str] = Field(description="Purchase Order number")
    CompanyAddress1: Optional[str] = Field(description="Primary address line of the company (Required but if not applicable, N/A)")
    CompanyAddress2: Optional[str] = Field(description="Secondary address line of the company")
    City: Optional[str] = Field(description="City name from the address")
    State: Optional[str] = Field(description="State or province name")
    Zip: Optional[str] = Field(description="Postal or ZIP code")
    Country: Optional[str] = Field(description="Country name")
    EmailInvoiceTo: Optional[str] = Field(description="Email address for invoice delivery (Required but if not applicable, N/A)")
    CustomerTitle: Optional[str] = Field(description="Title of the customer representative (Required but if not applicable, N/A)")
    DateSigned: Optional[datetime] = Field(description="Date when the document was signed (Required but if not applicable, N/A)")
    CreatedAt: Optional[datetime] = Field(description="Document creation timestamp (Required but if not applicable, N/A)")
    UpdatedAt: Optional[datetime] = Field(description="Last update timestamp (Required but if not applicable, N/A)") 
    
class DocumentExtraction(BaseModel):
    """Document extraction model for contract information"""
    CustomerName: str = Field(description="Name of the customer or company")
    AccountID: str = Field(description="Unique identifier for the customer account")
    Quote: Optional[str] = Field(description="Quote number reference", alias="Quote#")
    CommitmentTerms: str = Field(description="Terms of commitment specified in the contract")
    BuyingProgram: str = Field(description="Type of buying program or plan")
    CommitmentFee: float = Field(description="Fee amount for the commitment")
    SavingsPlanCredit: float = Field(description="Credit amount from savings plan")
    NetPayableFee: float = Field(description="Net fee amount payable")
    ContactName: str = Field(description="Name of the primary contact person")
    TermStartDate: datetime = Field(description="Start date of the contract term")
    RenewalDate: datetime = Field(description="Date when the contract is up for renewal")
    BillingTerms: str = Field(description="Terms and conditions for billing")
    PaymentTerms: str = Field(description="Terms and conditions for payment")
    PaymentMethod: str = Field(description="Method of payment specified")
    VATID: Optional[str] = Field(description="VAT identification number")
    PO: Optional[str] = Field(description="Purchase Order number")
    CompanyAddress1: str = Field(description="Primary address line of the company")
    CompanyAddress2: Optional[str] = Field(description="Secondary address line of the company")
    City: str = Field(description="City name from the address")
    State: str = Field(description="State or province name")
    Zip: str = Field(description="Postal or ZIP code")
    Country: str = Field(description="Country name")
    EmailInvoiceTo: str = Field(description="Email address for invoice delivery")
    CustomerTitle: str = Field(description="Title of the customer representative")
    DateSigned: datetime = Field(description="Date when the document was signed")
    CreatedAt: datetime = Field(description="Document creation timestamp")
    UpdatedAt: datetime = Field(description="Last update timestamp") 