name: Destroy AWS Resources

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Empty S3 bucket
        run: aws s3 rm s3://ai-doc-parser-s3 --recursive || true

      - name: Update Terraform configuration for deletion
        working-directory: ./terraform
        run: |
          if ! grep -q "force_delete = true" main.tf; then
            sed -i '/resource "aws_ecr_repository" "ai_doc_parser" {/a \ \ force_delete = true' main.tf
          fi
          if ! grep -q "force_destroy = true" main.tf; then
            sed -i '/resource "aws_s3_bucket" "ai_doc_parser" {/a \ \ force_destroy = true' main.tf
          fi
          
      - name: Apply configuration updates
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Destroy all resources
        working-directory: ./terraform
        run: terraform destroy -auto-approve
        env:
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
